Fixed action grep usage

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -51,8 +51,8 @@ jobs:
         run: |
           cd $TEST_DIR
           cat $RESULT_FILE;
-          sed -e '/Failed Assertions: /!d;  s/Failed Assertions: //' $RESULT_FILE > $FAILURE_CNT
-          sed -e '/Unexpected Errors: /!d;  s/Unexpected Errors: //' $RESULT_FILE > $UNEXPECTED_CNT
-          if [ `grep '^[^0]' $FAILURE_CNT -c` ]; then echo "Tests failed!"; exit 70; fi
-          if [ `grep '^[^0]' $UNEXPECTED_CNT -c` ]; then echo "Unexpected test errors"; exit 85; fi
+          sed -e '/Failed Assertions: /!d;  s/Failed Assertions: //' $RESULT_FILE | grep '^[^0]' -c > $FAILURE_CNT
+          sed -e '/Unexpected Errors: /!d;  s/Unexpected Errors: //' $RESULT_FILE | grep '^[^0]' -c > $UNEXPECTED_CNT
+          if [ `cat $FAILURE_CNT` != 0 ]; then echo "Tests failed!"; exit 70; fi
+          if [ `cat $UNEXPECTED_CNT` != 0 ]; then echo "Unexpected test errors"; exit 85; fi
           
